###############################################
############## BOUNTY SIGNS ####################
###############################################



############## DEBUG ##########################
locale: en
debug: false
log.recipes.enable: false