###############################################
############## BOUNTY SIGNS ####################
###############################################



############## DEBUG ##########################
locale: en
debug: true
log.recipes.enable: false