name: BountySigns
version: 1.0.0
main:  com.blocktyper.bountysigns.BountySignsPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Find the NPC on the sign.  Get the bounty.
commands:
  bounty-signs:
    description: main entry point.  run with no args for usage
  bnty: 
    description: short cut for /bounty-signs